@host=localhost:{{API_PORT}}

### Login Authentication

### login
POST http://{{host}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "12345678"
}

### List best Games

## best-ratsd | most-reviewed | popular
@ranking=most-reviewed
@quantity=10
GET http://{{host}}/games?ranking={{ranking}}&quantity={{quantity}}
Accept: application/json

### Get Gane Details

@id=25097
GET http://{{host}}/games/details/{{id}}
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

### Search Games

## @page=1 (optional) (default is 1)
## @pagesize=10 (optional) (default is 10)
@query=gta
GET http://{{host}}/games/search?query={{query}}
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

