@host=localhost:{{API_PORT}}

### Login Authentication

### login
POST http://{{host}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "12345678"
}

### List all current user Reviews

GET http://{{host}}/reviews/me
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

### List all game Reviews

@userId=19c1f635-6f0e-4b90-acf1-5eb9ab3efb9c
@gameId=25097
GET http://{{host}}/reviews?gameId={{gameId}}
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

### Create a new Review

POST http://{{host}}/reviews
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "title": "Amazing Game!",
    "content": "I had a fantastic time playing this game. Highly recommended!",
    "rating": 9.5,
    "gameId": "25097"

}

### Delete a Review

@reviewId=9b55ecb5-a13f-4ca9-a5b3-8f83eea59d37
DELETE http://{{host}}/reviews/{{reviewId}}
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

